customhost = "employee2.c7kn95m0dr8w.us-east-1.rds.amazonaws.com"
customuser = "aws_user2"
custompass = "bait3273"
customdb = "employee2"
custombucket = "simhongli-employee2"
customregion = "us-east-1"
